CREATE TABLE auth_user(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	username VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(100) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE auth_role(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(15) NOT NULL,
	level TINYINT(2) NOT NULL DEFAULT 99
);

CREATE TABLE auth_user_role(
	user_id INT UNSIGNED NOT NULL,
	role_id INT UNSIGNED NOT NULL,
	INDEX user_id(user_id) USING BTREE,
	INDEX role_id(role_id) USING BTREE,
	FOREIGN KEY (user_id) REFERENCES auth_user(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (role_id) REFERENCES auth_role(id) ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO auth_role (name, level) VALUES ('superadmin', 1), ('admin', 20), ('member', 99);

